### PR TITLE
Fix install example

### LINKED ISSUE #35: Update image repo in installation example
### What problem are you facing?

Hey guys, amazing work you've been doing here.
I see that #112 changed the image repo, so from version 0.4.0 onwards a change is needed in the installation example:

`image: crossplane/provider-terraform-controller:v0.5.0` -> `image: crossplanecontrib/provider-terraform-controller:v0.5.0`
`package: crossplane/provider-terraform:v0.5.0` -> `package: v/provider-terraform:v0.5.0`

### How could Crossplane help solve your problem?

n/a

### PR DESCRIPTION
**Pull request by ltdeoliveira**
Signed-off-by: ltdeoliveira <ltdeoliveira@gmail.com>

### Description of your changes

* Update image repo name to crossplanecontrib on installation example
* Update install example to use latest version
* Remove unnecessary `image` from ControllerConfig
Fixes #35 

I have:

- [ ] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

Applied the example on a personal cluster and successfully installed version v0.6.0.

### CODE REVIEW

**Comment by ltdeoliveira** [comment]
@ytsarev does the version and/or the image repo change for this repo?

**Comment by ytsarev** [comment]
Yes, see https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.2.0

it is `xpkg.upbound.io/upbound/provider-terraform:v0.2.0`

**Comment by ltdeoliveira** [comment]
> Yes, see https://marketplace.upbound.io/providers/upbound/provider-terraform/v0.2.0
> 
> it is `xpkg.upbound.io/upbound/provider-terraform:v0.2.0`

Thanks

**Review by ytsarev — APPROVED** [review]
Thank you!

**Pull request merged**
