### PR TITLE
Update to go1.21 and crossplane-runtime 1.15.1

### PR DESCRIPTION
**Pull request by bobh66**
### Description of your changes

Update to use go1.21 and crossplane-runtime 1.15.1

I have:

- [X] Run `make reviewable` to ensure this PR is ready for review.

### How has this code been tested

Deployed into a test cluster and verified that Workspace resources are created/reconciled/deleted successfully.

### CODE REVIEW

**Comment by ytsarev** [comment]
/test-examples="examples/workspace-inline-aws.yaml"

**Comment by ytsarev** [comment]
/test-examples="examples/workspace-inline-aws.yaml"

**Comment by ytsarev** [comment]
@bobh66 Looks like `go mod tidy` is required 

https://github.com/upbound/provider-terraform/actions/runs/8694401581
image

**Comment by ytsarev** [comment]
/test-examples="examples/workspace-inline-aws.yaml"

**Comment by bobh66** [comment]
/test-examples="examples/workspace-inline-aws.yaml"

**Comment by bobh66** [comment]
/test-examples="examples/workspace-inline-aws.yaml"

**Review by ytsarev — APPROVED** [review]
All good now, thanks for the updates!

**Pull request merged**
